content/api/1-pool.mdx
Removed "the" from double article "the a" under the "pool.on('acquire')" event.
=> fix double article under 'acquire' event

content/features/1-connecting.mdx
Should fix [this issue](https://github.com/brianc/node-postgres/issues/1617) asking for better docs concerning the use of unix sockets. Seems to be a common issue and the issue is over a year old.
=> Document access to unix sockets.

content/features/4-transactions.mdx
It's the one place you need a semicolon, otherwise you get the error:`(intermediate value) is not a function`
=> To prevent intermediate value is not a function

content/api/2-client.mdx
I fixed some typo  😊
I always thank you for what you made.👍
=> docs(2-client.mdx): fix typo 'e => err.stack' -> 'err => err.stack'

content/features/4-transactions.mdx
The `insertPhotoValues` variable on line 86 referenced `res` which is not declared. It should be declared on line 83 but is destructured into `rows`.
I chose to revert the destructured version to `res` so the syntax will look similar to the callback example above :)
=> Fix typo in transaction async/await example

content/features/3-pooling.mdx
Updated "console.log('async query finished)" to "console.log('async query finished')"
=> Fixed syntax error in 3-pooling.mdx

src/sortNavItems.js
I just realized my PR failed to build to prod, thought I'l fix it :)
I fixed the part where the error occurred, and refactored a bit.
Explanation:
I found that `allMdx.edges` doesn't always return in the same order. The previous code expects it to be in the order, e,g, '/', '/api', '/api/pool'. The root or prefix paths are expected to come before the subpaths. This means if the order becomes e.g. '/', '/api/pool', '/api', it would fail due to line 33 `...acc[`/${prefix}`` failed to spread since it wasn't declared before.
Also, I found that after editing the changes, line 26-28's if statement can be combined into the changes below.
=> Fix build error

src/templates/docs.js
Updates the code to set the title tag based on page titles instead of `metaTitle` of which only the Native page had one with a value of `bar`. 
Before:
After:
=> Use page title and site title in title tag

content/api/1-pool.mdx
All 3 arguments in the connect callback can be undefined, see relevant change to types here for a link to the instances in the relevant source code/tests.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41519
=> Made every arg in pool.connect callback optional

content/guides/1-project-structure.md
Removing `<summary>` was a bit of judgment call, but without a `<details>` element it doesn't render correctly. The previous note was just an italicized paragraph, so I opted for that.
=> Fix typo, formatting

content/api/2-client.mdx
Why:
node-postgres 8.0.0 introduced support for all tls.connect options for config.ssl.
This commit:
Makes reference to this in the Client constructor documentation.
=> Add note to client docs for tls.connect options

content/api/2-client.mdx
Added host to client config because I think it is missing.
=> Added host to client config

gatsby-config.js, package.json, src/components/mdxComponents/index.js, src/components/rightSidebar.js, yarn.lock
Fixes formatted text (e.g. inline code) being rendered as “[object Object]” (#84), and multiple text children (e.g. `new Pool([config: object])`, for some reason) being rendered with commas. Also now compatible with GitHub!
Can be used to add link icons beside each heading later by removing `icon: false` from its configuration (but needs additional CSS).
=> Use gatsby-remark-autolink-headers to get improved heading ids

content/features/2-queries.mdx
Copied code, didn't work. Fixed. Submitted.
Good job otherwise! :100:
=> fix: variable names in map fn for query examples

content/guides/3-upgrading.md
This is where I went looking for information about what broke in 8.
@eschwartz pointed me to the Announcements, which do contain full
details but were not a place I thought to look.
This PR includes the most critical breaking change in the "Upgrading"
section, with reference to the announcement for the details.
Fixes https://github.com/brianc/node-postgres/issues/2342
=> Include 8.0 in the Upgrading section

content/api/2-client.mdx
Simple documentation for the pass-through connection parameter added
in https://github.com/brianc/node-postgres/pull/2049.
The description is taken from https://www.postgresql.org/docs/current/runtime-config-client.html.
Closes https://github.com/brianc/node-postgres/issues/2381
=> Document idle_in_transaction_session_timeout

content/features/5-types.mdx
This commit removes an extra trailing comma the [snippet][docs] that demonstrates date/timestamp/timestamptz conversion. Copy/pasting the example caused a SQL syntax error.
[docs]: https://node-postgres.com/features/types
=> Remove invalid trailing comma in date example

content/api/2-client.mdx
Hi.
There is a problem with the constructor configuration of pg.Client (pg.Poll).
We would like you to reflect this fix so that you will soon notice that you can specify a dynamic password by specifying a function in the password property.
=> Added function to password property type of config

content/guides/1-project-structure.md
There are two variables named `res`. Fails responding back to user because it's using res from db instance. Renamed to `result` and it's now a working example.
=> Updated express example, now working.

content/api/3-result.mdx
=> Fix typo in pg.Result documentation

content/api/5-cursor.mdx
The callback is never called with [any argument at all](https://github.com/brianc/node-postgres/blob/master/packages/pg-cursor/index.js#L198-L214) and docs is misleading/outdated.
=> remove error argument from close callback

content/api/1-pool.mdx
Address issue mentioned in https://github.com/brianc/node-postgres/issues/2590
=> Add allowExitOnIdle to pool API documentation

content/features/6-ssl.mdx
I tripped over this case today when handling client code which used both `connectionString` and `ssl` configuration options and the former unexpectedly overrides the latter.
The relevant code that handles this is here:
https://github.com/brianc/node-postgres/blob/4b229275cfe41ca17b7d69bd39f91ada0068a5d0/packages/pg-connection-string/index.js#L68-L70
Other people with similar confusion:
https://github.com/brianc/node-postgres/issues/2375
https://github.com/brianc/node-postgres/issues/2380
=> Warn about mixed use of connectionString and ssl

content/api/2-client.mdx
If I get this right, the spot in the code to know for that is https://github.com/brianc/node-postgres/blob/947ccee346f0d598e135548e1e4936a9a008fc6f/packages/pg/lib/connection-parameters.js#L9
=> default database name depends on $PGUSER first, then $USER

content/features/3-pooling.mdx
The code in the `finally` block runs even if there was an error while executing the `catch` block, so the "async/await - check out a client" example can be simplified.
=> Simplified code example
